# This is a basic workflow to help you get started with Actions

name: CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  deploy:
        name: Deploy to Caprover
        runs-on: ubuntu-latest
        env:
            CAPROVER_APP: bashley
            CAPROVER_URL: ${{ secrets.CAPROVER_URL }}
            CAPROVER_PASSWORD: ${{ secrets.CAPROVER_PASSWORD }}
            CAPROVER_TOKEN_BASHLEY: ${{ secrets.CAPROVER_TOKEN_BASHLEY }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: 'Install caprover-cli'
              run: npm install -g caprover
            - name: 'Deploy'
              env:
                  CAPROVER_URL: ${{ env.CAPROVER_URL }}
                  CAPROVER_PASSWORD: ${{ env.CAPROVER_PASSWORD }}
                  CAPROVER_APP: ${{ env.CAPROVER_APP }}
                  CAPROVER_APP_TOKEN: ${{ env.CAPROVER_TOKEN_BASHLEY }}
#                   CAPROVER_IMAGE_NAME: img-captain-${{ env.CAPROVER_APP }}
              run: 'caprover deploy'
