# This is a basic workflow to help you get started with Actions

name: CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  deploy:
        name: Deploy to Caprover
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: 'Install caprover-cli'
              run: npm install -g caprover
            - name: 'Deploy'
              env:
                  CAPROVER_URL: ${{ secrets.CAPROVER_URL }}
                  CAPROVER_APP: bashley
                  CAPROVER_BRANCH: master                  
                  CAPROVER_APP_TOKEN: ${{ secrets.CAPROVER_TOKEN_BASHLEY 
              run: 'caprover deploy'
