# This is a basic workflow to help you get started with Actions

name: CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deploy:
        name: Deploy to Caprover
        runs-on: ubuntu-latest

        env:
            CAPROVER_SERVER: ${{ secrets.CAPROVER_SERVER }}
            CAPROVER_TOKEN_BASHLEY: ${{ secrets.CAPROVER_TOKEN_BASHLEY }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: 'Install caprover-cli'
              run: npm install -g caprover
            - name: 'Deploy'
              env:
                  APP_NAME: bashley
                  APP_SERVER: ${{ env.CAPROVER_SERVER }}
                  CAPROVER_APP_TOKEN: ${{ env.CAPROVER_TOKEN_BASHLEY }}
              run: 'caprover deploy --caproverUrl=$APP_SERVER --appName=$APP_NAME'
